// Default runtime settings for ProjectChat.

export const LEGACY_CHAT_ALLOWED_FILE_TYPES = [
  "image/*",
  ".wps",
  ".doc",
  ".docx",
  ".pdf",
  ".txt",
  ".csv",
  ".xlsx",
  ".xls",
];

export const CHAT_SETTINGS_DEFAULTS = {
  chat_mode: "system",
  external_agent_type: "codex_cli",
  local_connector_id: "",
  connector_workspace_path: "",
  connector_sandbox_mode: "workspace-write",
  connector_sandbox_mode_explicit: false,
  selected_employee_id: "",
  selected_employee_ids: [],
  employee_coordination_mode: "auto",
  provider_id: "",
  model_name: "",
  temperature: 0.1,
  system_prompt: "",
  auto_use_tools: false,
  auto_use_tools_explicit: false,
  enabled_project_tool_names: [],
  tool_priority: [],
  history_limit: 20,
  upload_file_limit: 6,
  max_file_size_mb: 15,
  doc_max_chars_per_file: 1200,
  doc_max_chars_total: 3000,
  allowed_file_types: [],
  high_risk_tool_confirm: true,
  answer_style: "concise",
  prefer_conclusion_first: true,
  task_tree_enabled: true,
  task_tree_auto_generate: true,
  image_resolution: "1080x1080",
  image_aspect_ratio: "1:1",
  image_generate_four_views: false,
  image_style: "auto",
  image_quality: "high",
  video_aspect_ratio: "16:9",
  video_style: "cinematic",
  video_duration_seconds: 5,
  video_motion_strength: "medium",
};
