"""Static external skill catalogs used for employee skill suggestion."""

from __future__ import annotations

from typing import Any


EXTERNAL_SKILL_CATALOG: list[dict[str, Any]] = [
    {
        "id": "clawhub-ai-ivangdavila-ui",
        "name": "UI",
        "skill_name": "UI 设计与界面一致性",
        "summary": "聚焦界面审美、一致性、信息层次和组件级视觉表达。",
        "source_id": "clawhub_ivangdavila",
        "source_label": "Vett / clawhub.ai / ivangdavila",
        "source_url": "https://vett.sh/skills/clawhub.ai/ivangdavila/ui",
        "preview_url": "https://vett.sh/skills/clawhub.ai/ivangdavila/ui",
        "industries": ["frontend", "web", "design-system", "ui"],
        "keywords": ["ui", "design", "interface", "layout", "design-system", "视觉", "界面", "设计", "布局", "组件", "交互"],
    },
    {
        "id": "clawhub-ai-ivangdavila-css",
        "name": "CSS",
        "skill_name": "CSS 与样式工程化",
        "summary": "覆盖现代 CSS、布局系统、样式组织和常见视觉问题修复。",
        "source_id": "clawhub_ivangdavila",
        "source_label": "Vett / clawhub.ai / ivangdavila",
        "source_url": "https://vett.sh/skills/clawhub.ai/ivangdavila/css",
        "preview_url": "https://vett.sh/skills/clawhub.ai/ivangdavila/css",
        "industries": ["frontend", "web", "css", "ui"],
        "keywords": ["css", "style", "styles", "responsive", "layout", "animation", "html", "样式", "布局", "响应式", "动画"],
    },
    {
        "id": "clawhub-ai-ivangdavila-vue",
        "name": "Vue",
        "skill_name": "Vue 深度应用",
        "summary": "聚焦 Vue 组件设计、Composition API、工程化和常见陷阱规避。",
        "source_id": "clawhub_ivangdavila",
        "source_label": "Vett / clawhub.ai / ivangdavila",
        "source_url": "https://vett.sh/skills/clawhub.ai/ivangdavila/vue",
        "preview_url": "https://vett.sh/skills/clawhub.ai/ivangdavila/vue",
        "industries": ["frontend", "web", "vue", "javascript"],
        "keywords": ["vue", "vue3", "composition-api", "frontend", "component", "组件", "前端"],
    },
    {
        "id": "clawhub-ai-ivangdavila-nodejs",
        "name": "Node.js",
        "skill_name": "JavaScript / Node.js 工程实践",
        "summary": "适合服务端 JS、工具链、构建脚本和运行时治理相关任务。",
        "source_id": "clawhub_ivangdavila",
        "source_label": "Vett / clawhub.ai / ivangdavila",
        "source_url": "https://vett.sh/skills/clawhub.ai/ivangdavila/nodejs",
        "preview_url": "https://vett.sh/skills/clawhub.ai/ivangdavila/nodejs",
        "industries": ["javascript", "nodejs", "tooling", "web"],
        "keywords": ["javascript", "js", "node", "nodejs", "tooling", "build", "runtime", "脚本", "构建", "工程化"],
    },
    {
        "id": "clawhub-ai-ivangdavila-chrome",
        "name": "Chrome",
        "skill_name": "Chrome DevTools 与浏览器排查",
        "summary": "偏浏览器调试、性能排查、网络与渲染问题定位。",
        "source_id": "clawhub_ivangdavila",
        "source_label": "Vett / clawhub.ai / ivangdavila",
        "source_url": "https://vett.sh/skills/clawhub.ai/ivangdavila/chrome",
        "preview_url": "https://vett.sh/skills/clawhub.ai/ivangdavila/chrome",
        "industries": ["frontend", "web", "browser", "performance"],
        "keywords": ["chrome", "devtools", "browser", "performance", "debug", "network", "render", "浏览器", "调试", "性能", "排查"],
    },
    {
        "id": "clawhub-ai-ivangdavila-software-architect",
        "name": "Software Architect",
        "skill_name": "软件架构设计",
        "summary": "适合技术选型、模块拆分、架构边界和系统演进相关任务。",
        "source_id": "clawhub_ivangdavila",
        "source_label": "Vett / clawhub.ai / ivangdavila",
        "source_url": "https://vett.sh/skills/clawhub.ai/ivangdavila/software-architect",
        "preview_url": "https://vett.sh/skills/clawhub.ai/ivangdavila/software-architect",
        "industries": ["architecture", "system-design", "web", "engineering"],
        "keywords": ["architect", "architecture", "system-design", "design", "scalability", "选型", "架构", "系统设计", "拆分"],
    },
    {
        "id": "clawhub-ai-ivangdavila-website",
        "name": "Website",
        "skill_name": "网站交付与前端工程落地",
        "summary": "偏站点开发、页面交付、部署前检查和整站协同。",
        "source_id": "clawhub_ivangdavila",
        "source_label": "Vett / clawhub.ai / ivangdavila",
        "source_url": "https://vett.sh/skills/clawhub.ai/ivangdavila/website",
        "preview_url": "https://vett.sh/skills/clawhub.ai/ivangdavila/website",
        "industries": ["frontend", "web", "delivery", "website"],
        "keywords": ["website", "web", "frontend", "delivery", "deploy", "html", "css", "站点", "网站", "前端", "交付"],
    },
]
